# Assignment 2 for Course 1MS041
Make         sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline         and your highest score will be used.

---
## Assignment 2, PROBLEM 1
Maximum Points = 8


A courier company operates a fleet of delivery trucks that make deliveries to different parts of the city. The trucks are equipped with GPS tracking devices that record the location of each truck at regular intervals. The locations are divided into three regions: downtown, the suburbs, and the countryside. The following table shows the probabilities of a truck transitioning between these regions at each time step:

| Current region | Probability of transitioning to downtown | Probability of transitioning to the suburbs | Probability of transitioning to the countryside |
|----------------|--------------------------------------------|-----------------------------------------------|------------------------------------------------|
| Downtown       | 0.3                                      | 0.4                                           | 0.3                                            |
| Suburbs        | 0.2                                      | 0.5                                           | 0.3                                            |
| Countryside    | 0.4                                      | 0.3                                           | 0.3                                            |

1. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region after two time steps? [1.5p]
2. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region **the first time** after two time steps? [1.5p]
3. Is this Markov chain irreducible? [1.5p]
4. What is the stationary distribution? [1.5p]
5. Advanced question: What is the expected number of steps until the first time one enters the downtown region having started in the suburbs region. Hint: to get within 1 decimal point, it is enough to compute the probabilities for hitting times below 30. [2p]



In [1]:
# Part 1
import numpy as np
P = np.matrix([[0.3, 0.4, 0.3],
              [0.2, 0.5, 0.3],
              [0.4, 0.3, 0.3]])

# Fill in the answer to part 1 below as a decimal number
p0 = np.array([0,1,0])
p2 = p0*(P**2)
print(p2)
problem1_p1 = 0.28

[[0.28 0.42 0.3 ]]


In [2]:
# Part 2

# Fill in the answer to part 2 below as a decimal number
problem1_p2 = 0.22

In [3]:
# Part 3

# Fill in the answer to part 3 below as a boolean
problem1_irreducible = True

In [4]:
# Part 4

# Fill in the answer to part 4 below
# the answer should be a numpy array of length 3
# make sure that the entries sums to 1!
evals,evecs = np.linalg.eig(P.T)
first_evec = evecs[:,0]
problem1_stationary = np.array(first_evec) / np.sum(first_evec)
print(problem1_stationary)

[[0.28888889]
 [0.41111111]
 [0.3       ]]


In [5]:
# Part 5

# Fill in the answer to part 5 below
# That is, the expected number of steps as a decimal number
problem1_ET = 3.836

---
## Assignment 2, PROBLEM 2
Maximum Points = 8


A healthcare organization is interested in understanding the relationship between the number of visits to the doctors office and certain patient characteristics. 
They have collected data on the number of visits (for a year) for a sample of patients and have included the following variables

* ofp : number of physician office visits
* ofnp : number of nonphysician office visits
* opp : number of physician outpatient visits
* opnp : number of nonphysician outpatient visits
* emr : number of emergency room visits
* hosp : number of hospitalizations
* exclhlth : the person is of excellent health (self-perceived)
* poorhealth : the person is of poor health (self-perceived)
* numchron : number of chronic conditions
* adldiff : the person has a condition that limits activities of daily living ?
* noreast : the person is from the north east region
* midwest : the person is from the midwest region
* west : the person is from the west region
* age : age in years (divided by 10)
* male : is the person male ?
* married : is the person married ?
* school : number of years of education
* faminc : family income in 10000$
* employed : is the person employed ?
* privins : is the person covered by private health insurance?
* medicaid : is the person covered by medicaid ?

Decide which patient features are resonable to use to predict the target "number of physician office visits". Hint: should we really use the "ofnp" etc variables?

Since the target variable is counts, a reasonable loss function is to consider the target variable as Poisson distributed where the parameter follows $\lambda = \exp(\alpha \cdot x + \beta)$ where $\alpha$ is a vector (slope) and $\beta$ is a number (intercept). That is, the parameter is the exponential of a linear function. The reason we chose this as our parameter, is that it is always positive which is when the Poisson distribution is defined. To be specific we make the following assumption about our conditional density of $Y \mid X$,
$$
    f_{Y \mid X} (y,x) = \frac{\lambda^{y} e^{-\lambda}}{y !}, \quad \lambda(x) = \exp(\alpha \cdot x + \beta).
$$

Recall from the lecture notes, (4.2) that in this case we should consider the log-loss (entropy) and that according to (4.2.1 Maximum Likelihood and regression) we can consider the conditional log-likelihood. Follow the steps of Example 1 and Example 2 in section (4.2) to derive the loss that needs to be minimized.

Hint: when taking the log of the conditional density you will find that the term that contains the $y!$ does not depend on $\lambda$ and as such does not depend on $\alpha,\beta$, it can thus be discarded. This will be essential due to numerical issues with factorials.

Instructions:

1. Load the file `data/visits_clean.csv`, follow the instructions in the code cell of how this should happen [1.5p]
2. Create the `problem2_X` and the `problem2_y` as numpy arrays with `problem2_X` being the features and `problem2_y` being the target. Do the standard train-test split with 80% training data and 20% testing data. Store these in the variables defined in the cells. [1.5p]
3. Implement $loss$ inside the class `PoissonRegression` by writing down the loss to be minimized, I have provided a formula for the $\lambda$ that you can use. [1.5p]
4. Now use the `PoissonRegression` class to train a Poisson regression model on the training data. [1.5p]
5. Compute the mean absolute error of your prediction on the test set and use Hoeffdings inequality to produce a 95\% confidence interval for the mean absolute error. We can make the assumption that the error is bounded by 70 for simplicity. [2p]


In [6]:
# Part 1
import csv
import numpy as np

# As in assignment 1 we will load the header into header and data into data
# this time you will have to parse the data such that each data entry is a float
# and that the problem2_data is a numpy array of shape (n_samples,n_columns)
# where n_columns is the number of columns and should have the same length as
# the list of strings header. n_samples is how many rows of data we had.
# If you cannot find the file, check the starting package as it should be updated
# if not, go to the github repo and pull it

# The autograder does not accept pandas as a solution to this problem.
# data/visits_clean.csv

with open("data/visits_clean.csv") as f:
    rows = [row for row in csv.reader(f)]

problem2_header = rows[0][0].split(" ") #List of strings

problem2_data = np.array([row[0].split(" ") for row in rows[1:]]).astype(float) #A numpy array of shape n_samples n_columns

print(problem2_data)

[[ 5.  0.  0. ...  1.  1.  0.]
 [ 1.  0.  2. ...  0.  1.  0.]
 [13.  0.  0. ...  0.  0.  1.]
 ...
 [10.  0. 20. ...  0.  1.  0.]
 [16.  1.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]]


In [7]:
# Part 2

# Fill in your X and y below
problem2_X = np.delete(problem2_data, [0, 1, 3, 16], axis=1)
problem2_y = problem2_data[:,0]
'''
ofp
ofnp
opnp
'''

print(problem2_y)
# Split the data into train and randomly using for instance
# np.random.shuffle indices and indexing the first 80% as the train data
# keep the train size as 0.8 rounded up to the nearest integer sample
#problem2_X_train, problem2_X_test, problem2_y_train, problem2_y_test = train_test_split(problem2_X,problem2_y, train_size=0.8, random_state=42)

total_len = problem2_X.shape[0]
indices = np.arange(total_len)
np.random.shuffle(indices)
train_len = int(np.round(0.8*total_len))

problem2_X_train = problem2_X[indices[:train_len]]
problem2_y_train = problem2_y[indices[:train_len]]

problem2_X_test = problem2_X[indices[train_len:]]
problem2_y_test = problem2_y[indices[train_len:]]


[ 5.  1. 13. ... 10. 16.  0.]


In [8]:
# Part 3

# Fill in the function loss below

class PoissonRegression(object):
    def __init__(self):
        self.coeffs = None
        self.result = None
    
    # define the objective/cost/loss function we want to minimise
    def loss(self,X,Y,coeffs):
        # The parameter lambda for the given X and the proposed values 
        # of the coefficients, here coeff[:-1] represent alpha 
        # and coeff[-1] represent beta
        alpha = coeffs[:-1]
        beta = coeffs[-1]
        lam = np.exp(np.dot(X, alpha) + beta)
        
        # use the Y variable that is available here to define 
        # the loss function, return the value of the loss for
        # this Y and for this parameter lam defined above
        return - np.mean(Y*np.log(lam) - lam)

    def fit(self,X,Y):
        import numpy as np
        from scipy import optimize

        #Use the loss above together with an optimization method from scipy
        #to find the coefficients of the model
        #this is prepared for you below
        opt_loss = lambda coeffs: self.loss(X,Y,coeffs)
        print(opt_loss)
        initial_arguments = np.zeros(shape=X.shape[1]+1) # initial guess as 0
        self.result = optimize.minimize(opt_loss, initial_arguments,method='cg')
        self.coeffs = self.result.x
    
    def predict(self,X):
        #Use the trained model to predict Y
        if (self.coeffs is not None):
            return np.exp(np.dot(X,self.coeffs[:-1])+self.coeffs[-1])

In [9]:
# Part 4

# Initialize your PoissonRegression model
problem2_model = PoissonRegression()

# Fit your initialized model on the training data

problem2_model.fit(problem2_X_train, problem2_y_train)

# This is to make sure that everything went well, 
# check that success is True
print(problem2_model.result)

<function PoissonRegression.fit.<locals>.<lambda> at 0x1470f3ec0>
 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: -4.8845953610394846
       x: [ 6.468e-03  1.120e-02 ...  1.730e-01  1.575e+00]
     nit: 767
     jac: [-3.576e-07 -2.384e-06 ...  1.192e-07 -4.411e-06]
    nfev: 25042
    njev: 1318


In [10]:
# Part 5

# Put the computed mean absolute error in the variable below
predict_y = problem2_model.predict(problem2_X_test)

problem2_metric = np.mean((np.abs(problem2_y_test-predict_y)))
print(problem2_metric)
# Put a confidence interval in the variable below by using Hoeffdings inequality using the bounds
# a = 0, b=70 (roughly 5 days between visits as minimum)
# the variable should contain a tuple representing the confidence interval of the form (l_edge,r_edge)

"""
Compute the mean absolute error of your prediction on the test set and use Hoeffdings inequality 
to produce a 95\% confidence interval for the mean absolute error.
We can make the assumption that the error is bounded by 70 for simplicity. [2p]
"""

a = 0
b = 70
n = problem2_X_test.shape[0]
alfa = 0.05
err = (b-a)*np.sqrt(np.log(2/alfa)/(2*n))

problem2_interval = (problem2_metric-err, problem2_metric+err)
print(problem2_interval)

4.073224744287117
(0.8703325597576721, 7.2761169288165615)


---
## Assignment 2, PROBLEM 3
Maximum Points = 8


## Random variable generation and transformation

The purpose of this problem is to show that you can implement your own sampler, this will be built in the following three steps:

1. [2p] Implement a Linear Congruential Generator where you tested out a good combination (a large $M$ with $a,b$ satisfying the Hull-Dobell (Thm 6.8)) of parameters. Follow the instructions in the code block.
2. [2p] Using a generator construct random numbers from the uniform $[0,1]$ distribution.
3. [4p] Using a uniform $[0,1]$ random generator, generate samples from 

$$p_0(x) = \frac{\pi}{2}|\sin(2\pi x)|, \quad x \in [0,1] \enspace .$$

Using the **Accept-Reject** sampler (**Algorithm 1** in TFDS notes) with sampling density given by the uniform $[0,1]$ distribution.

In [11]:

def problem3_LCG(size=None, seed = 0):
    """
    A linear congruential generator that generates pseudo random numbers according to size.
    
    Parameters
    -------------
    size : an integer denoting how many samples should be produced
    seed : the starting point of the LCG, i.e. u0 in the notes.

    Returns
    -------------
    out : a list of the pseudo random numbers
    """
    
    x = seed # the seed
    m = 2**16+1
    a = 75
    b = 74
    retValue = [x % m]  # start the list with x=x0
    for _ in range(2, size+1, 1):
        x = (a * x + b) % m # the generator, using modular arithmetic
        retValue.append(x) # append the new x to the list
    return retValue

In [12]:
print(problem3_LCG(size=3, seed=0))

[0, 74, 5624]


In [13]:

def problem3_uniform(generator=None, period = 1, size=None, seed=0):
    """
    Takes a generator and produces samples from the uniform [0,1] distribution according
    to size.
    
    Parameters
    -------------
    generator : a function of type generator(size,seed) and produces the same result as problem1_LCG, i.e. pseudo random numbers in the range {0,1,...,period-1}
    period : the period of the generator
    seed : the seed to be used in the generator provided
    size : an integer denoting how many samples should be produced
    
    Returns
    --------------
    out : a list of the uniform pseudo random numbers
    """
    
    return [x/period for x in generator(size, seed)]

In [14]:
import math
def problem3_accept_reject(uniformGenerator=None, n_iterations=None, seed=0):
    """
    Takes a generator that produces uniform pseudo random [0,1] numbers 
    and produces samples from (pi/2)*abs(sin(x*2*pi)) using an Accept-Reject
    sampler with the uniform distribution as the proposal distribution.
    Runs n_iterations
    
    Parameters
    -------------
    generator : a function of the type generator(size,seed) that produces uniform pseudo random
    numbers from [0,1]
    seed : the seed to be used in the generator provided
    n_iterations : an integer denoting how many attempts should be made in the accept-reject sampler
    
    Returns
    --------------
    out : a list of the pseudo random numbers with the specified distribution
    """
    
    fx = lambda x: (math.pi/2)*abs(math.sin(x*2*math.pi))

    m = math.pi/2

    acc_numbers = []
    x = seed
    for _ in range(n_iterations):
        x = uniformGenerator(1, x)[0]
        u = m*uniformGenerator(1,x)[0]
        if u <= fx(x):
            acc_numbers.append(x)
        x = u
    
    return acc_numbers

---
#### Local Test for Assignment 2, PROBLEM 3
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [15]:

# If you managed to solve all three parts you can test the following code to see if it runs
# you have to change the period to match your LCG though, this is marked as XXX.
# It is a very good idea to check these things using the histogram function in sagemath
# try with a larger number of samples, up to 10000 should run

print("LCG output: %s" % problem3_LCG(size=10, seed = 1))

period = 2**16+1

print("Uniform sampler %s" % problem3_uniform(generator=problem3_LCG, period = period, size=10, seed=1))

uniform_sampler = lambda size,seed: problem3_uniform(generator=problem3_LCG, period = period, size=size, seed=seed)

print("Accept-Reject sampler %s" % problem3_accept_reject(uniformGenerator = uniform_sampler,n_iterations=20,seed=1))

LCG output: [1, 149, 11249, 57305, 38044, 35283, 24819, 26463, 18689, 25472]
Uniform sampler [1.5258556235409006e-05, 0.0022735248790759417, 0.1716434990921159, 0.8743915650701131, 0.5804965134199002, 0.538367639653936, 0.3787021072066161, 0.4037871736576285, 0.2851671574835589, 0.3886659444283382]
Accept-Reject sampler [1.5258556235409006e-05, 5.5803341454910996e-15, 2.0408306457638568e-24, 7.463692345474016e-34, 2.7296093158693775e-43, 9.982682394189302e-53, 3.6508502225534567e-62, 1.3351829519565771e-71, 4.883009180115377e-81, 1.7858061038114945e-90, 6.531020775871318e-100, 2.3885142000480737e-109, 8.735234934343282e-119, 3.194635784733266e-128, 1.1683369564536616e-137, 4.2728227434833425e-147, 1.5626497215876284e-156, 5.714896917037093e-166, 2.0900427217417578e-175, 7.643669942117595e-185]


In [16]:

# If however you did not manage to implement either part 1 or part 2 but still want to check part 3, you can run the code below

def testUniformGenerator(size,seed):
    import random
    random.seed(seed)
    
    return [random.uniform(0,1) for s in range(size)]

print("Accept-Reject sampler %s" % problem3_accept_reject(uniformGenerator=testUniformGenerator, n_iterations=20, seed=1))

Accept-Reject sampler [0.14255194400746352, 0.8606641102717673, 0.7069021336891445, 0.7663114717503429, 0.7396761872809192, 0.3192516361229536, 0.7202382955177504, 0.8101434099887752]
